public with sharing class QuoteLineItemClass {
	
	// For test code coverage
	public QuoteLineItemClass(String forTest){}
	
/*	QuoteLineItem qli;
	public QuoteLineItemClass(ApexPages.StandardController controller)
	{
		qli = (QuoteLineItem)controller.getrecord();
	}
	
	public pagereference redirectEdiAll()
	{
		Pagereference p = new Pagereference('/apex/QuoteLineEditPage?id='+qli.QuoteId+'&retURL=%2F'+qli.QuoteId+'&quoteId='+qli.QuoteId+'&sfdc.override=1');
		p.setredirect(true);
		return p;
	}*/  
}