<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Partner Portal</title>
<style type="text/css">
body {
	background-color: #FFF;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333;
}

img
{  border-style: none;
}

a {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	color: #333;
}
a:hover {
	color: #09F;
}
.t1 {
	background-color: #ffffff; border: 1px #bbbbbb solid; padding: 5px;
	} 
	
.t2 {
	background-color: #dddddd;
	} 
	
.t3 {
	background-color: #dddddd; border: 1px #bbbbbb solid;
	} 

</style>
</head>

<body>
								                
				                <table border="0">
				                	<tr>
				                		<td valign="top">
								                <table border="0" cellspacing="0" cellpadding="0" width="302" height="100%">
								                  	<tr>
									    			  <td><img src="/resource/1304119455000/partner_Title_NewDeal" alt="New Deal Registration" width="302" height="32" align="top" /></td>
									    			</tr>
									    			<tr>
								                      <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">1. <a href="/00Q/e?retURL=%2F00Q%2Fo" target="_parent">Create a New Deal Registration</a></td>
								                    </tr>
								                    <tr>
								                      <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">2. <a href="/00Q?fcf=00B80000007r68H" target="_parent">View Pending Deal Registrations</a></td>
								                    </tr>
								                    <tr>
								                      <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">3. <a href="/00Q?fcf=00B80000007r68G" target="_parent">View Approved Deal Registrations</a></td>
								
								                    </tr>
								                </table>
				                		</td>
				                		<td valign="top">
				                				<table border="0" cellspacing="0" cellpadding="0" width="302" height="100%">
													<tr>
									    			  <td><img src="/resource/1304120048000/partner_Title_SalesTools" alt="Sales Tools" width="302" height="32" align="top" /></td>
									    			</tr>
									    			<tr>
													  <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">1. <a href="https://na6.salesforce.com/sfc/#workspaces" target="_parent">Sales Tools</a></td>
													</tr>
													<tr>
													  <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">2. <a href="http://www.appdynamics.com/customers.php" target="_blank">Customer Testimonials Videos</a></td>
													</tr>
													<tr>
													  <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">3. <a href="http://appdynamics.com/partnerwebinars/" target="_blank">Sales Training Videos</a></td>
												    </tr>
												    <tr>
													  <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">4. <a href="http://portal.appdynamics.com/" target="_blank">Trial License (Operations) Portal</a></td>
												    </tr>
												    <tr>
													  <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">5. <a href="http://www.appdynamics.com/products-whats-new.php" target="_blank">Latest Product Information</a></td>
												    </tr>
												</table>
				                		</td>
				                		<td valign="top">
				                				<table border="0" cellpadding="0" cellspacing="0" width="302" height="100%">
									                  <tr>
									    			  	<td><img src="/resource/1304120397000/partner_Title_SalesProcess" alt="Sales Process" width="302" height="32" align="top" /></a></td>
									    			  </tr>
									    			  <tr>
									                    <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">1.  <a href="http://help.appdynamics.com/home" target="_blank">AppDynamics Help Center</a></td>
													  </tr>
									                  <tr>
									                    <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">2.  <a href="http://help.appdynamics.com/entries/204649-controller-hardware-requirements" target="_blank">Controller Sizing Guide</a></td>
									                  </tr>
									                  <tr>
									                    <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">3.  <a href="http://www.appdynamics.com/products-free-download.php" target="_blank">AppDynamics Lite Resources</a></td>
									                  </tr>
									                  <tr>
									                    <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">4.  <a href="http://liteforums.appdynamics.com/" target="_blank">Lite User Community</a></td>
									                  </tr>
									        	</table>
				                		</td>
				                	</tr>
				                	<tr>
				                		<td valign="top">
				                				<table border="0" cellpadding="0" cellspacing="0" width="302" height="100%">
										              <tr>
									    			  	<td><img src="/resource/1304120213000/partner_Title_Training" alt="Training" width="302" height="32" align="top" /></td>
									    			  </tr>
									    			  <tr>
										                <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">1. <a href="http://www.appdynamics.com/products-whats-new.php" target="_blank">Latest Product Information</a></td>
										              </tr>
										              <tr>
														<td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">2. <a href="http://appdynamics.com/partnerwebinars/" target="_blank">Sales Training Videos</a></td>
										              </tr>
										              <tr>
										                <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">3. <a href="http://www.youtube.com/user/AppDynamics?ob=5#p/u" target="_blank">AppDynamics YouTube Training</a></td>
										              </tr>
										              <tr>
										                <td class="t1" onmouseover="style.backgroundColor='#C3DFFC';" onmouseout="style.backgroundColor='#ffffff'">4. <a href="http://www.marketo.com/demo/sales-insight-demo/" target="_blank">Marketo Sales Insight Training Video</a></td>
										              </tr>
										        </table>
				                		</td>
				                		<td valign="top">
				                			&nbsp;	
				                		</td>
				                		<td>&nbsp;</td>
				                	</tr>
				                </table>
				                
				                
				                
			                 				
			                 	
			               		
			               				

					    		
    	
</body>
</html>
